//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputData", Namespace="http://schemas.datacontract.org/2004/07/WcfService3appTEST")]
    [System.SerializableAttribute()]
    public partial class OutputData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] leftGyroXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] leftGyroYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] leftGyroZField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] responsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double turnsLeftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double turnsRightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] leftGyroX {
            get {
                return this.leftGyroXField;
            }
            set {
                if ((object.ReferenceEquals(this.leftGyroXField, value) != true)) {
                    this.leftGyroXField = value;
                    this.RaisePropertyChanged("leftGyroX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] leftGyroY {
            get {
                return this.leftGyroYField;
            }
            set {
                if ((object.ReferenceEquals(this.leftGyroYField, value) != true)) {
                    this.leftGyroYField = value;
                    this.RaisePropertyChanged("leftGyroY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] leftGyroZ {
            get {
                return this.leftGyroZField;
            }
            set {
                if ((object.ReferenceEquals(this.leftGyroZField, value) != true)) {
                    this.leftGyroZField = value;
                    this.RaisePropertyChanged("leftGyroZ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] responses {
            get {
                return this.responsesField;
            }
            set {
                if ((object.ReferenceEquals(this.responsesField, value) != true)) {
                    this.responsesField = value;
                    this.RaisePropertyChanged("responses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double turnsLeft {
            get {
                return this.turnsLeftField;
            }
            set {
                if ((this.turnsLeftField.Equals(value) != true)) {
                    this.turnsLeftField = value;
                    this.RaisePropertyChanged("turnsLeft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double turnsRight {
            get {
                return this.turnsRightField;
            }
            set {
                if ((this.turnsRightField.Equals(value) != true)) {
                    this.turnsRightField = value;
                    this.RaisePropertyChanged("turnsRight");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DetectTurns", ReplyAction="http://tempuri.org/IService1/DetectTurnsResponse")]
        WindowsFormsApp1.ServiceReference1.OutputData DetectTurns();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DetectTurns", ReplyAction="http://tempuri.org/IService1/DetectTurnsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OutputData> DetectTurnsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendPackage", ReplyAction="http://tempuri.org/IService1/SendPackageResponse")]
        void SendPackage(byte[] rawData, int numberOfpackages);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SendPackage", ReplyAction="http://tempuri.org/IService1/SendPackageResponse")]
        System.Threading.Tasks.Task SendPackageAsync(byte[] rawData, int numberOfpackages);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WindowsFormsApp1.ServiceReference1.OutputData DetectTurns() {
            return base.Channel.DetectTurns();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.OutputData> DetectTurnsAsync() {
            return base.Channel.DetectTurnsAsync();
        }
        
        public void SendPackage(byte[] rawData, int numberOfpackages) {
            base.Channel.SendPackage(rawData, numberOfpackages);
        }
        
        public System.Threading.Tasks.Task SendPackageAsync(byte[] rawData, int numberOfpackages) {
            return base.Channel.SendPackageAsync(rawData, numberOfpackages);
        }
    }
}
